### PR TITLE
Update Board and Change Board Colors

### PR DESCRIPTION
**Pull request by kelseyroy**
Adds
- private methods to Wordle.UI so that it can now DisplayEmptyBoard, UpdateBoard, RenderRow and RenderCell.
- Global wordScoreArray to keep track of accepted words + their letter evaluations
- guessCount to keep track of number of accepted guesses
- functionality to utilize letter evaluations to provide colorful console feedback to player about letter accuracy

Changes
- EvaluateLetter to accept a string rather than a Guess class.

https://user-images.githubusercontent.com/89801075/235794824-d5191ae4-72a2-4e4d-8a09-20a4b895853a.mov

I would love to get your thoughts on whether Wordle.UI is the correct place for this board functionality or if some belongs in the Wordle.Domain project? Also, is there better logic for UpdateBoard (instead of the two while loops)?

### CODE REVIEW

**Comment by Aoxian** [comment]
>  I would love to get your thoughts on whether Wordle.UI is the correct place for this board functionality or if some belongs in the Wordle.Domain project?

"Board functionality", I do not think there is anything functional happening here, its presentation. This could live in a presentation layer, which is fully tested, that sits between the core functionality and the actual UI (which is just printing things, and getting input).  The program is so small, that just including the presentation layer as part of the UI makes sense to me, vs. putting it into the main programming.

**Comment by kelseyroy** [comment]
> "Board functionality", I do not think there is anything functional happening here, its presentation. 

This was my instinct too. I like your idea of having a testable presentation layer, I think the hardest part of building this was all the times I had to run it in the console to verify that it looks as expected. Tests would've made that process much easier, especially if I'm just testing that RenderCell is being called 5 times or something relatively simple like that.

**Review by t-keazirian — APPROVED** [review]
Screenshot 2023-05-03 at 9 08 26 AM

I may have cheated 😆 great refactoring - I like all the methods for rendering the row and the cell.

This is looking awesome so far!

**Comment by ghost** [comment]
This is so freaking cool!!!!

**Pull request merged**
